### ISSUE TITLE
Make it clearer when a proposal was created "on behalf of" someone else

### ISSUE THREAD

**Issue by PierreMesure** [consuldemocracy/consuldemocracy#3696]
### User Story

As a participatory budget organiser, we allow people to leave proposals physically in a box in the public library. We also organise several physical events during which people can contribute with ideas but we don't necessarily make them create an account and add their projects on the platform.

As a participatory budget organiser, I want to be able to create proposals and budget investments on behalf of someone and that the identity of that person be clearly visible.

Currently, it is possible to add a proposal on behalf of a group or an organisation and this works perfectly fine for our use case as well:

What we would like to improve is the visibility of the proposal author's name in the list of proposals and on the proposal's page.

### Why is this Needed?

To make sure that there is no misunderstanding and so it doesn't look like a majority of the proposals have been left by the admin.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

#### Creation form

![Capture d’écran 2019-09-12 à 09 01 58](https://user-images.githubusercontent.com/7223028/64762279-219aea00-d53e-11e9-8eaf-af20fcbb55e0.png)

#### Proposal page
You can then see that the proposal was written on behalf of someone at the bottom:

![Capture d’écran 2019-09-12 à 09 00 48](https://user-images.githubusercontent.com/7223028/64762304-30819c80-d53e-11e9-8618-07f9d5d51075.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

![Capture d’écran 2019-09-12 à 09 06 55](https://user-images.githubusercontent.com/7223028/64762443-80f8fa00-d53e-11e9-8779-2148b1579727.png)

![Capture d’écran 2019-09-12 à 09 12 04](https://user-images.githubusercontent.com/7223028/64762451-85251780-d53e-11e9-9003-7b79c1bee2ee.png)

### Definition of Done
- text present in the list view
- text present in the proposal view
- (optional) change the avatar letter so it matches the proposal author and not the one who wrote it on behalf
- (optional) remove the text at the bottom of the proposal which is quite confusing currently

**Comment by matisnape** [comment]
I think I'm gonna take it :)

**Comment by PierreMesure** [comment]
Great to hear Anna! Don't hesitate to ask for help!

**Comment by matisnape** [comment]
@PierreMesure I did a clean install (with migrations) and when I start server I get the following error:
`NoMethodError (undefined method `value' for nil:NilClass):

app/models/widget/feed.rb:7:in `active?'
app/models/widget/feed.rb:17:in `block in active'
app/models/widget/feed.rb:15:in `collect'
app/models/widget/feed.rb:15:in `active'
app/controllers/welcome_controller.rb:12:in `index'`

any tips?

**Comment by matisnape** [comment]
BTW, I found 2 bugs on master
1) visual in route /management/budgets/:id/investments/new https://monosnap.com/file/fHqPiDojfRwjFUaPjoQQ9K1q105a0f 
2) some problem with partial in Management http://localhost:3000/management/budgets/:id/investments/:id https://monosnap.com/file/AKU4LfRFVhEn1bmNAcGTrbS4aYOdLh

Are you aware of those? If you can reproduce, can I create a new issue and try to fix it?
