### ISSUE TITLE
Flaky spec: Budget::Ballot::Line Validations Approval voting validates votes when creating lines at the same time

### ISSUE THREAD

**Issue by javierm** [consuldemocracy/consuldemocracy#4903]
## References

* This test, which is in the `spec/models/budget/ballot/line_spec.rb` file, has failed a few times, like in our [test run 3882, job 3](https://github.com/consul/consul/runs/7877363054) (see the [test run 3882 job log](https://github.com/consul/consul/files/9359242/run_3882_job_3.txt)), which run on commit consul/consul@4a786e4a7

## Failure
```
  1) Budget::Ballot::Line Validations Approval voting validates votes when creating lines at the same time
     Failure/Error: ballot.lock!

     RuntimeError:
       Locking a record with unpersisted changes is not supported. Use `save` to persist the changes, or `reload` to discard them explicitly.
     # ./app/models/budget/ballot/line.rb:22:in `check_enough_resources'
     # ./spec/models/budget/ballot/line_spec.rb:71:in `block (6 levels) in <top (required)>'
```

**Comment by lucialuzuriaga** [comment]
Closing as fixed.
