### ISSUE TITLE
Flaky spec: Multitenancy PostgreSQL extensions work for tenants

### ISSUE THREAD

**Issue by javierm** [consuldemocracy/consuldemocracy#5787]
## References

* This test, which is in the `spec/system/multitenancy_spec.rb` file, has failed in our [test run 8274, job 2](https://github.com/consuldemocracy/consuldemocracy/actions/runs/11747689680/job/32730131655) (see the [test run 8274, job 2 log](https://github.com/user-attachments/files/17685172/test_run_8274_job_2.txt))

## Failure

```
1) Multitenancy PostgreSQL extensions work for tenants
     Failure/Error: expect(page).to have_content "Proposal created successfully."
       expected to find text "Proposal created successfully." in "Language: \n        \nEnglish\nDeutsch\nEspañol\nFrançais\nNederlands\nPortuguês brasileiro\n中文\n       Notifications\nMy content\nMy account\nSign out\nDebates\nYou are in\nProposals\nVoting\nCollaborative legislation\nParticipatory budgeting\nSDG\nHelp\nProposals\nCreate new proposal\nHow do citizen proposals work?\nRecommendations for creating a proposal\nDo not use capital letters for the proposal title or for whole sentences. On the internet, this is considered shouting. And nobody likes being shouted at.\nAny proposal or comment suggesting illegal action will be deleted, as well as those intending to sabotage the debate spaces. Anything else is allowed.\nEnjoy this space and the voices that fill it. It belongs to you too.\n×\n1 error prevented this Proposal from being saved.\nPlease check the marked fields to know how to correct them:\nREQUIRED FIELDS\nProposal title\nProposal summary\n(maximum 200 characters)\ntsvector for María the Martian\nProposal text\n    Format\n    ◢\n  If you are human, ignore this field\nOPTIONAL FIELDS\nExternal video URL\nYou may add a link to YouTube or Vimeo\nDescriptive image\nYou can upload one image of following content types: jpg, up to 1 MB.\nAdd image\nDocuments\nYou can upload up to a maximum of 3 documents of following content types: pdf, up to 3 MB per file.\nAdd new document\nTags\nTag this proposal. You can choose from proposed categories or add your own\nCategories\n\nFull name of the person submitting the proposal\n(individually or as representative of a collective; will not be displayed publically)\ncan't be blank, is too short (minimum is 6 characters)\nSustainable Development Goals and Targets\nYou can choose one or several SDGs aligned with your citizen proposal\nGoals and Targets\nYou can introduce the code of a specific goal/target or a text to find one. For more information visit the SDG help page.\nI agree to the Privacy Policy and the Terms and conditions of use\nOpen government\nThis portal uses the CONSUL DEMOCRACY application which is open-source software.\nParticipation\nDecide how to shape the city you want to live in.\nCONSUL DEMOCRACY, 2024 Privacy Policy Terms and conditions of use Accessibility"

     [Screenshot Image]: /home/runner/work/consuldemocracy/consuldemocracy/tmp/capybara/failures_r_spec_example_groups_multitenancy_postgre_sql_extensions_work_for_tenants_555.png


     # ./spec/system/multitenancy_spec.rb:54:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:95:in `with_subdomain'
```

## Cause

The relevant parts of the failure are:

```
1 error prevented this Proposal from being saved
```

And:

```
Full name of the person submitting the proposal\n(individually or as representative of a collective; will not be displayed publically)\ncan't be blank, is too short (minimum is 6 characters)
```

This means that, when creating the proposal, there's a validation check for the presence of the responsible name, which is only checked then `Setting["feature.user.skip_verification"]` is `nil`. Since tenants created in our tests use the default settings, this setting should be `true` in this case.

In the past, this test also failed occasionally due to requests leaking in multitenancy tests; that was solved in pull request #5754.

So a possible for this test failure is that a previous test might have finished without finishing a certain request. In the particular tests of the run, the following tests were executed right before this failure:

```
Ballots Permissions Unselected investments                                                                                                  
Ballots Permissions User is organization
Ballots Permissions Different district
Ballots Permissions Edge case voting a non-elegible investment                                                                              
Ballots Permissions Insufficient funds (added after create)
Ballots Hide money Do not show prices on sidebar or ballot show
Ballots Lines Load finds ballot lines using budget slug
Ballots Load finds ballot using budget slug                    
Multitenancy Disabled features                                       
Multitenancy PostgreSQL extensions work for tenants 
```

Among these tests, at the very least the test `Ballots Hide money Do not show prices on sidebar or ballot show` contains an AJAX request (done by the code `click_link "Check my votes"`) that doesn't need to finish in order for the test to pass. It's possible that request is interfering with the request done to a different subdomain in the multitenancy tests.

There might be other possible causes for this failure, though.

## How to fix

As a first step, when the test fails, we need to check tests that were executed before it and make sure all of them finish their requests.

**Comment by ritankarsaha** [comment]
@javierm Fixed the issue and opened a PR for the same at #5931
